name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master # Triggers on push/merge to main or master branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Fix execution permissions
        run: chmod +x node_modules/.bin/vite

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The directory Vite builds your static site into
          branch: gh-pages # The branch to publish to
